import React, { createContext, useContext, useState, useCallback, useMemo } from 'react';

export type Language = 'pt-BR' | 'en' | 'es' | 'fr' | 'ar';

interface LanguageContextProps {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

interface LanguageProviderProps {
  children: React.ReactNode;
}

const translations = {
  'pt-BR': {
    navigation: {
      home: 'Início',
      bible: 'Bíblia',
      community: 'Comunidade',
      profile: 'Perfil',
      login: 'Entrar',
      register: 'Cadastrar',
      logout: 'Sair',
      search: 'Pesquisar',
    },
    bible: {
      selectBook: 'Selecionar Livro',
      selectChapter: 'Selecionar Capítulo',
      oldTestament: 'Antigo Testamento',
      newTestament: 'Novo Testamento',
      chapterNotFound: 'Capítulo não encontrado',
      tryAnotherChapter: 'Por favor selecione outro livro ou capítulo.',
      verseSaved: 'Versículo Salvo',
      copy: 'Copiar versículo',
      highlight: 'Destacar versículo',
      share: 'Compartilhar versículo',
    },
    settings: {
      title: 'Configurações',
      profile: 'Meu Perfil',
      language: 'Idioma',
      systemLanguage: 'Usar idioma do sistema',
      notifications: 'Notificações',
      dailyReminders: 'Receber lembretes de leitura diária',
      autoScroll: 'Auto-rolagem',
      autoScrollReading: 'Rolar automaticamente durante a leitura',
      updateError: 'Erro ao atualizar configuração',
      fontSize: 'Tamanho da Fonte',
      fontSizeChanged: 'Tamanho da fonte alterado',
      'fontSize.small': 'Pequeno',
      'fontSize.medium': 'Médio',
      'fontSize.large': 'Grande',
    },
    profile: {
      title: 'Meu Perfil',
      readingStreak: 'Sequência de Leitura',
      days: 'dias',
      dailyGoal: 'Meta Diária',
      bestStreak: 'Melhor sequência',
      level: 'Nível',
      experience: 'Experiência',
      editProfile: 'Editar Perfil',
    },
    community: {
      title: 'Comunidade',
      latestPosts: 'Últimas Publicações',
      popularTopics: 'Tópicos Populares',
      createPost: 'Criar Publicação',
    },
    auth: {
      loginTitle: 'Entrar',
      registerTitle: 'Cadastrar',
      email: 'Email',
      password: 'Senha',
      confirmPassword: 'Confirmar Senha',
      displayName: 'Nome de Exibição',
      loginButton: 'Entrar',
      registerButton: 'Cadastrar',
      forgotPassword: 'Esqueceu a senha?',
      resetPassword: 'Redefinir Senha',
    },
    common: {
      close: 'Fechar',
      save: 'Salvar',
      edit: 'Editar',
      delete: 'Excluir',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      loading: 'Carregando...',
      error: 'Erro',
      success: 'Sucesso',
      and: 'e',
    },
  },
  en: {
    navigation: {
      home: 'Home',
      bible: 'Bible',
      community: 'Community',
      profile: 'Profile',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      search: 'Search',
    },
    bible: {
      selectBook: 'Select Book',
      selectChapter: 'Select Chapter',
      oldTestament: 'Old Testament',
      newTestament: 'New Testament',
      chapterNotFound: 'Chapter not found',
      tryAnotherChapter: 'Please select another book or chapter.',
      verseSaved: 'Verse Saved',
      copy: 'Copy verse',
      highlight: 'Highlight verse',
      share: 'Share verse',
    },
    settings: {
      title: 'Settings',
      profile: 'My Profile',
      language: 'Language',
      systemLanguage: 'Use system language',
      notifications: 'Notifications',
      dailyReminders: 'Receive daily reading reminders',
      autoScroll: 'Auto-scroll',
      autoScrollReading: 'Automatically scroll during reading',
      updateError: 'Error updating setting',
      fontSize: 'Font Size',
      fontSizeChanged: 'Font size changed',
      'fontSize.small': 'Small',
      'fontSize.medium': 'Medium',
      'fontSize.large': 'Large',
    },
    profile: {
      title: 'My Profile',
      readingStreak: 'Reading Streak',
      days: 'days',
      dailyGoal: 'Daily Goal',
      bestStreak: 'Best streak',
      level: 'Level',
      experience: 'Experience',
      editProfile: 'Edit Profile',
    },
    community: {
      title: 'Community',
      latestPosts: 'Latest Posts',
      popularTopics: 'Popular Topics',
      createPost: 'Create Post',
    },
    auth: {
      loginTitle: 'Login',
      registerTitle: 'Register',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      displayName: 'Display Name',
      loginButton: 'Login',
      registerButton: 'Register',
      forgotPassword: 'Forgot password?',
      resetPassword: 'Reset Password',
    },
    common: {
      close: 'Close',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      cancel: 'Cancel',
      confirm: 'Confirm',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      and: 'and',
    },
  },
  es: {
    navigation: {
      home: 'Inicio',
      bible: 'Biblia',
      community: 'Comunidad',
      profile: 'Perfil',
      login: 'Iniciar sesión',
      register: 'Registrarse',
      logout: 'Cerrar sesión',
      search: 'Buscar',
    },
    bible: {
      selectBook: 'Seleccionar Libro',
      selectChapter: 'Seleccionar Capítulo',
      oldTestament: 'Antiguo Testamento',
      newTestament: 'Nuevo Testamento',
      chapterNotFound: 'Capítulo no encontrado',
      tryAnotherChapter: 'Por favor seleccione otro libro o capítulo.',
      verseSaved: 'Versículo Guardado',
      copy: 'Copiar versículo',
      highlight: 'Destacar versículo',
      share: 'Compartir versículo',
    },
    settings: {
      title: 'Configuraciones',
      profile: 'Mi Perfil',
      language: 'Idioma',
      systemLanguage: 'Usar idioma del sistema',
      notifications: 'Notificaciones',
      dailyReminders: 'Recibir recordatorios de lectura diaria',
      autoScroll: 'Auto-scroll',
      autoScrollReading: 'Desplazamiento automático durante la lectura',
      updateError: 'Error al actualizar la configuración',
      fontSize: 'Tamaño de fuente',
      fontSizeChanged: 'Tamaño de fuente cambiado',
      'fontSize.small': 'Pequeña',
      'fontSize.medium': 'Mediana',
      'fontSize.large': 'Grande',
    },
    profile: {
      title: 'Mi Perfil',
      readingStreak: 'Racha de Lectura',
      days: 'días',
      dailyGoal: 'Meta Diaria',
      bestStreak: 'Mejor racha',
      level: 'Nivel',
      experience: 'Experiencia',
      editProfile: 'Editar Perfil',
    },
    community: {
      title: 'Comunidad',
      latestPosts: 'Últimas Publicaciones',
      popularTopics: 'Temas Populares',
      createPost: 'Crear Publicación',
    },
    auth: {
      loginTitle: 'Iniciar sesión',
      registerTitle: 'Registrarse',
      email: 'Correo electrónico',
      password: 'Contraseña',
      confirmPassword: 'Confirmar Contraseña',
      displayName: 'Nombre para mostrar',
      loginButton: 'Iniciar sesión',
      registerButton: 'Registrarse',
      forgotPassword: '¿Olvidaste tu contraseña?',
      resetPassword: 'Restablecer la contraseña',
    },
    common: {
      close: 'Cerrar',
      save: 'Guardar',
      edit: 'Editar',
      delete: 'Eliminar',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      loading: 'Cargando...',
      error: 'Error',
      success: 'Éxito',
      and: 'y',
    },
  },
  fr: {
    navigation: {
      home: 'Accueil',
      bible: 'Bible',
      community: 'Communauté',
      profile: 'Profil',
      login: 'Se connecter',
      register: 'S\'inscrire',
      logout: 'Se déconnecter',
      search: 'Rechercher',
    },
    bible: {
      selectBook: 'Sélectionner un livre',
      selectChapter: 'Sélectionner un chapitre',
      oldTestament: 'Ancien Testament',
      newTestament: 'Nouveau Testament',
      chapterNotFound: 'Chapitre non trouvé',
      tryAnotherChapter: 'Veuillez sélectionner un autre livre ou chapitre.',
      verseSaved: 'Verset Sauvé',
      copy: 'Copier le verset',
      highlight: 'Surligner le verset',
      share: 'Partager le verset',
    },
    settings: {
      title: 'Paramètres',
      profile: 'Mon Profil',
      language: 'Langue',
      systemLanguage: 'Utiliser la langue du système',
      notifications: 'Notifications',
      dailyReminders: 'Recevoir des rappels de lecture quotidienne',
      autoScroll: 'Défilement automatique',
      autoScrollReading: 'Défilement automatique pendant la lecture',
      updateError: 'Erreur lors de la mise à jour du paramètre',
       fontSize: 'Taille de police',
      fontSizeChanged: 'Taille de police modifiée',
      'fontSize.small': 'Petite',
      'fontSize.medium': 'Moyenne',
      'fontSize.large': 'Grande',
    },
    profile: {
      title: 'Mon Profil',
      readingStreak: 'Série de Lecture',
      days: 'jours',
      dailyGoal: 'Objectif Quotidien',
      bestStreak: 'Meilleure série',
      level: 'Niveau',
      experience: 'Expérience',
      editProfile: 'Modifier le Profil',
    },
    community: {
      title: 'Communauté',
      latestPosts: 'Derniers Messages',
      popularTopics: 'Sujets Populaires',
      createPost: 'Créer un Message',
    },
    auth: {
      loginTitle: 'Se connecter',
      registerTitle: 'S\'inscrire',
      email: 'Email',
      password: 'Mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      displayName: 'Nom d\'affichage',
      loginButton: 'Se connecter',
      registerButton: 'S\'inscrire',
      forgotPassword: 'Mot de passe oublié ?',
      resetPassword: 'Réinitialiser le mot de passe',
    },
    common: {
      close: 'Fermer',
      save: 'Enregistrer',
      edit: 'Modifier',
      delete: 'Supprimer',
      cancel: 'Annuler',
      confirm: 'Confirmer',
      loading: 'Chargement...',
      error: 'Erreur',
      success: 'Succès',
      and: 'et',
    },
  },
  ar: {
    navigation: {
      home: 'الرئيسية',
      bible: 'الكتاب المقدس',
      community: 'المجتمع',
      profile: 'الملف الشخصي',
      login: 'تسجيل الدخول',
      register: 'تسجيل',
      logout: 'تسجيل الخروج',
      search: 'بحث',
    },
    bible: {
      selectBook: 'اختر كتابا',
      selectChapter: 'اختر فصلا',
      oldTestament: 'العهد القديم',
      newTestament: 'العهد الجديد',
      chapterNotFound: 'الفصل غير موجود',
      tryAnotherChapter: 'الرجاء اختيار كتاب أو فصل آخر.',
      verseSaved: 'الآية محفوظة',
      copy: 'نسخ الآية',
      highlight: 'تمييز الآية',
      share: 'مشاركة الآية',
    },
    settings: {
      title: 'الإعدادات',
      profile: 'ملفي الشخصي',
      language: 'اللغة',
      systemLanguage: 'استخدام لغة النظام',
      notifications: 'الإشعارات',
      dailyReminders: 'تلقي تذكيرات القراءة اليومية',
      autoScroll: 'التمرير التلقائي',
      autoScrollReading: 'التمرير تلقائيا أثناء القراءة',
      updateError: 'خطأ في تحديث الإعداد',
      fontSize: 'حجم الخط',
      fontSizeChanged: 'تم تغيير حجم الخط',
      'fontSize.small': 'صغير',
      'fontSize.medium': 'متوسط',
      'fontSize.large': 'كبير',
    },
    profile: {
      title: 'ملفي الشخصي',
      readingStreak: 'سلسلة القراءة',
      days: 'أيام',
      dailyGoal: 'الهدف اليومي',
      bestStreak: 'أفضل سلسلة',
      level: 'المستوى',
      experience: 'الخبرة',
      editProfile: 'تعديل الملف الشخصي',
    },
    community: {
      title: 'المجتمع',
      latestPosts: 'أحدث المشاركات',
      popularTopics: 'المواضيع الشائعة',
      createPost: 'إنشاء مشاركة',
    },
    auth: {
      loginTitle: 'تسجيل الدخول',
      registerTitle: 'تسجيل',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      displayName: 'اسم العرض',
      loginButton: 'تسجيل الدخول',
      registerButton: 'تسجيل',
      forgotPassword: 'هل نسيت كلمة المرور؟',
      resetPassword: 'إعادة تعيين كلمة المرور',
    },
    common: {
      close: 'إغلاق',
      save: 'حفظ',
      edit: 'تعديل',
      delete: 'حذف',
      cancel: 'إلغاء',
      confirm: 'تأكيد',
      loading: 'جار التحميل...',
      error: 'خطأ',
      success: 'نجاح',
      and: 'و',
    },
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>((localStorage.getItem('language') as Language) || navigator.language.slice(0, 2) as Language || 'en');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = useCallback((key: string) => {
    return translations[language]?.[key] || key;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
