
// Map between API book IDs and database book IDs
export const bookIdMapping: Record<string, string> = {
  'gn': 'genesis',
  'ex': 'exodus',
  'lv': 'leviticus',
  'nm': 'numbers',
  'dt': 'deuteronomy',
  'js': 'joshua',
  'jud': 'judges',
  'rt': 'ruth',
  '1sm': '1samuel',
  '2sm': '2samuel',
  '1kgs': '1kings',
  '2kgs': '2kings',
  '1ch': '1chronicles',
  '2ch': '2chronicles',
  'ezr': 'ezra',
  'ne': 'nehemiah',
  'et': 'esther',
  'job': 'job',
  'ps': 'psalms',
  'prv': 'proverbs',
  'ec': 'ecclesiastes',
  'so': 'songofsolomon',
  'is': 'isaiah',
  'jr': 'jeremiah',
  'lm': 'lamentations',
  'ez': 'ezekiel',
  'dn': 'daniel',
  'ho': 'hosea',
  'jl': 'joel',
  'am': 'amos',
  'ob': 'obadiah',
  'jn': 'jonah',
  'mi': 'micah',
  'na': 'nahum',
  'hk': 'habakkuk',
  'zp': 'zephaniah',
  'hg': 'haggai',
  'zc': 'zechariah',
  'ml': 'malachi',
  'mt': 'matthew',
  'mk': 'mark',
  'lk': 'luke',
  'jo': 'john',
  'act': 'acts',
  'rm': 'romans',
  '1co': '1corinthians',
  '2co': '2corinthians',
  'gl': 'galatians',
  'eph': 'ephesians',
  'ph': 'philippians',
  'cl': 'colossians',
  '1ts': '1thessalonians',
  '2ts': '2thessalonians',
  '1tm': '1timothy',
  '2tm': '2timothy',
  'tt': 'titus',
  'phm': 'philemon',
  'hb': 'hebrews',
  'jm': 'james',
  '1pe': '1peter',
  '2pe': '2peter',
  '1jo': '1john',
  '2jo': '2john',
  '3jo': '3john',
  'jd': 'jude',
  're': 'revelation',
};

// Database book IDs to API IDs (reverse mapping)
export const reverseBookIdMapping: Record<string, string> = Object.fromEntries(
  Object.entries(bookIdMapping).map(([k, v]) => [v, k])
);
