// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwgljnfvkdkrodzcyxai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3Z2xqbmZ2a2Rrcm9kemN5eGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDk1MTIsImV4cCI6MjA2MDQ4NTUxMn0.3-OuQBbc5mPNUSTjBm1Q0xISmRxdyhH0txJtFDoBOeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);